### ISSUE TITLE
076Test_procedure

### ISSUE THREAD

**Issue by FujiZ** [romise/ComplingTest#3]
如果char的位宽为1字节的话，赋值可能会导致截断。所以{a  38  b  6  -49}也是一个可以接受的答案

**Comment by iromise** [comment]
我是按照char是8位无符号整数处理的，即大小为0-255，所以结果是那个。不知道你的处理方式是？

**Comment by FujiZ** [comment]
我按照signed char来做的，然后就是上面的结果

**Comment by iromise** [comment]
那应该也是对的~
